/** Chuỗi giao diện tiếng Việt có dấu — dùng xuyên suốt frontend. */
export const vi = {
  appName: "Trò chuyện",
  loading: "Đang tải…",
  login: {
    title: "Đăng nhập",
    saasTagline: "Kết nối mọi cuộc trò chuyện",
    emailLabel: "Email hoặc tên đăng nhập",
    emailRequired: "Vui lòng nhập email hoặc tên đăng nhập",
    passwordLabel: "Mật khẩu",
    passwordRequired: "Vui lòng nhập mật khẩu",
    showPassword: "Hiện mật khẩu",
    hidePassword: "Ẩn mật khẩu",
    submit: "Đăng nhập",
    success: "Đăng nhập thành công",
    fail: "Đăng nhập thất bại",
    noAccount: "Chưa có tài khoản?",
    registerLink: "Đăng ký ngay",
    subtitle: "Chào mừng trở lại",
    dividerOr: "hoặc",
    continueGoogle: "Tiếp tục với Google",
    continueGithub: "Tiếp tục với GitHub",
    socialComingSoon: "Đăng nhập mạng xã hội sẽ có trong bản cập nhật tới.",
  },
  register: {
    title: "Đăng ký tài khoản",
    username: "Tên đăng nhập",
    usernameRequired: "Vui lòng nhập tên đăng nhập",
    email: "Email",
    emailRequired: "Vui lòng nhập email",
    emailInvalid: "Email không hợp lệ",
    password: "Mật khẩu",
    passwordRequired: "Vui lòng nhập mật khẩu",
    passwordMin: "Mật khẩu tối thiểu 6 ký tự",
    confirm: "Nhập lại mật khẩu",
    confirmRequired: "Vui lòng xác nhận mật khẩu",
    mismatch: "Mật khẩu xác nhận không khớp",
    submit: "Đăng ký",
    success: "Đăng ký thành công, vui lòng đăng nhập",
    fail: "Đăng ký thất bại",
    hasAccount: "Đã có tài khoản?",
    loginLink: "Đăng nhập",
    subtitle: "Tạo tài khoản mới",
  },
  chat: {
    directFallback: "Trò chuyện 1-1",
    greeting: (name: string) => `Xin chào, ${name}`,
    noRoom: "Chưa chọn phòng",
    settings: "Cài đặt",
    themeDark: "Giao diện tối",
    desktopNotify: "Thông báo desktop (tab ẩn)",
    notifyDenied: "Trình duyệt từ chối hoặc chưa cấp quyền thông báo",
    soundNotify: "Âm báo tin mới",
    languageNote: "Ngôn ngữ: Tiếng Việt",
    searchPlaceholder: "Lọc theo tên hoặc email…",
    search: "Tìm",
    searchUsersTitle: "Tìm người dùng",
    userDiscoveryHint:
      "Danh sách người dùng trên hệ thống. Kéo xuống cuối danh sách để tải thêm (mỗi lần tối đa 40 người).",
    noSearch: "Không có kết quả",
    outgoing: (n: number) => `Danh sách chờ (${n})`,
    outgoingEmpty: "Không có lời mời đang chờ",
    waitingAccept: "Đang chờ chấp nhận",
    incoming: (n: number) => `Lời mời đến (${n})`,
    incomingEmpty: "Không có lời mời",
    previewTitle: "Xem trước ảnh",
    roomInfoDirect: "Thông tin người dùng",
    roomInfoGroup: "Thành viên trong nhóm",
    noRoomInfo: "Chưa chọn phòng để xem thông tin",
    noName: "Không có tên",
    noEmail: "Không có email",
    chatTypeDirect: "Loại chat: 1-1",
    roomId: "Mã phòng",
    addMemberTitle: "Thêm thành viên vào nhóm",
    addMemberOnlyGroup: "Chỉ hỗ trợ thêm thành viên cho nhóm chat",
    memberCount: (n: number) => `Tổng số thành viên: ${n}`,
    addMemberBtn: "Thêm thành viên",
    noMembers: "Không có thành viên",
    allFriendsInGroup: "Tất cả bạn bè đã có trong nhóm",
    loadingSidebar: "Đang tải danh sách…",
  },
  sidebar: {
    groupRoomsTitle: "Phòng nhóm",
    newRoomPlaceholder: "Tên phòng mới",
    createBtn: "Tạo",
    noGroupRooms: "Chưa có phòng nhóm",
    friends: (n: number) => `Bạn bè (${n})`,
    noFriends: "Chưa có bạn bè",
    unfriendTitle: "Xóa kết bạn?",
    unfriendDesc: (username: string) =>
      `Bạn chắc chắn muốn xóa ${username} khỏi danh sách bạn bè?`,
    delete: "Xóa",
    cancel: "Hủy",
  },
  compose: {
    placeholder: "Nhập tin nhắn, emoji hoặc chú thích kèm file…",
  },
  messageList: {
    recall: "Thu hồi tin nhắn",
    empty: "Chưa có tin nhắn nào",
    zoomImage: "Phóng to",
    readDirect: "Đã xem",
    readGroupAll: (readCount: number) => `Đã xem (${readCount})`,
    readGroupPartial: (readCount: number, total: number) => `Đã xem ${readCount}/${total}`,
  },
  errors: {
    generic: "Đã có lỗi xảy ra",
    loadOlder: "Không tải thêm tin nhắn cũ",
    loadRooms: "Không tải được danh sách phòng",
    loadFriends: "Không tải được danh sách bạn bè",
    loadUserBrowse: "Không tải được danh sách người dùng",
    loadIncoming: "Không tải được lời mời kết bạn",
    loadOutgoing: "Không tải được danh sách chờ",
    socket: (msg: string) => `Lỗi socket: ${msg}`,
    loadHistory: "Không tải được lịch sử tin nhắn",
    joinRoom: "Không vào được phòng",
    recall: "Thu hồi thất bại",
    createRoomOk: "Tạo phòng thành công",
    createRoomFail: "Tạo phòng thất bại",
    sendImageFail: "Gửi ảnh thất bại",
    uploadImageFail: "Tải ảnh lên thất bại",
    needTextOrMedia: "Nhập tin nhắn hoặc chọn ảnh",
    sendTextFail: "Gửi tin nhắn thất bại",
    pickRoom: "Chọn phòng trước",
    sendFileFail: "Gửi file thất bại",
    uploadFileFail: "Tải file lên thất bại",
    pickImageFile: "Vui lòng chọn file ảnh",
    userNotFound: "Không tìm thấy người dùng",
    inviteSent: "Đã gửi lời mời kết bạn",
    inviteFail: "Gửi lời mời thất bại",
    accepted: "Đã chấp nhận lời mời",
    rejected: "Đã từ chối lời mời",
    requestUpdateFail: "Cập nhật lời mời thất bại",
    unfriendOk: "Đã xóa kết bạn",
    unfriendFail: "Xóa kết bạn thất bại",
    openDirectFail: "Không mở được chat 1-1",
    memberAdded: "Đã thêm thành viên vào nhóm",
    memberAddFail: "Thêm thành viên thất bại",
  },
  notify: {
    friendRequest: "Bạn vừa nhận lời mời kết bạn mới",
    friendsUpdated: "Danh sách bạn bè đã được cập nhật",
    friendshipRemoved: "Một mối quan hệ bạn bè vừa bị xóa",
  },
  preview: {
    recalled: "Tin nhắn đã được thu hồi",
    image: "Hình ảnh",
    video: "Video",
    audio: "Âm thanh",
    message: "Tin nhắn",
  },
} as const;
